version: '3'

services:
  dragonblock_mysql:
    image: mysql/mysql-server:latest
    container_name: DragonBlockMySQL
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dragonblock_db
      MYSQL_USER: simple_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./MySQL/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - ./MySQL/mysql_data:/var/lib/mysql

  dragonblock_flask:
    build:
      context: ./Flask
      dockerfile: Dockerfile
    container_name: DragonBlockFlask
    command: /bin/sh /ContainerFiles/entrypoint.sh
    ports:
      - "80:80"
    depends_on:
      - dragonblock_mysql
    volumes:
      - ./Flask/ContainerFiles:/ContainerFiles

  dragonblock_truffle:
    build:
      context: ./Truffle
      dockerfile: Dockerfile
    container_name: DragonBlockTruffle 
    ports:
      - "5000:5000"
    volumes:
      - ./Truffle/ContainerFiles:/ContainerFiles/